name: Update Oktagon Calendar

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Repository checkout
      uses: actions/checkout@v4
      
    - name: Python einrichten
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Pakete installieren
      run: |
        pip install requests beautifulsoup4 pytz
        
    - name: Skript ausf√ºhren
      run: python generate_calendar.py
      
    - name: Kalender hochladen
      uses: actions/upload-artifact@v4
      with:
        name: oktagon-kalender
        path: oktagon_kalender.ics
